package com.picenter.picdb.dao;

import com.picenter.picdb.model.Picuser;
import com.picenter.picdb.model.PicuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PicuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    long countByExample(PicuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    int deleteByExample(PicuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    int insert(Picuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    int insertSelective(Picuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    List<Picuser> selectByExample(PicuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    Picuser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Picuser record, @Param("example") PicuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Picuser record, @Param("example") PicuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Picuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Picuser record);
}