package com.picenter.picdb.model;

public class Picuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picuser.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picuser.uname
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picuser.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picuser.vip
     *
     * @mbg.generated
     */
    private Boolean vip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picuser.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picuser.uid
     *
     * @return the value of picuser.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picuser.uid
     *
     * @param uid the value for picuser.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picuser.uname
     *
     * @return the value of picuser.uname
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picuser.uname
     *
     * @param uname the value for picuser.uname
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picuser.age
     *
     * @return the value of picuser.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picuser.age
     *
     * @param age the value for picuser.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picuser.vip
     *
     * @return the value of picuser.vip
     *
     * @mbg.generated
     */
    public Boolean getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picuser.vip
     *
     * @param vip the value for picuser.vip
     *
     * @mbg.generated
     */
    public void setVip(Boolean vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picuser.gender
     *
     * @return the value of picuser.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picuser.gender
     *
     * @param gender the value for picuser.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }
}